name: publish

on:
  release:
    types: [published, created, prereleased, released]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for OIDC

concurrency:
  group: publish-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm -s vitest run --reporter=dot
        env:
          CI: true

      # npm publish
      - name: publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            npm publish --access public --provenance --tag next
          else
            npm publish --access public --provenance
          fi

      # JSR publish (OIDC, no secret needed once linked)
      - name: publish to JSR
        run: pnpm dlx jsr publish
