name: release-please

on:
  push:
    branches: [main] # updates/opens the release PR when commits land on main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
    steps:
      - id: rp
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json

  publish:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm -s vitest run --reporter=dot
        env:
          CI: true

      - name: publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            npm publish --access public --provenance --tag next
          else
            npm publish --access public --provenance
          fi

      - name: publish to JSR
        run: pnpm dlx jsr publish
